# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b344667e04c0dd67082f6a3b65d9be67256d5f6db7af5ebeadb48f231f25fd73127ea414e96f38cc00ad2906be62e5d30c539138b1125932c8cb293f0cbe704

test:
  secret_key_base: 3efcd6b2570a383b66163a3fa52d618e2acec71a642d02599a83d892da41c1b3f7448ca1016e2825e3afb8cb28389b35c73aefb5eb845afb0721f3737be3b931

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
